/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sherry_ffmpegdemo_FfmpegKit_OnExecListener */

#ifndef _Included_com_sherry_ffmpegdemo_FfmpegKit_OnExecListener
#define _Included_com_sherry_ffmpegdemo_FfmpegKit_OnExecListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
