/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sherry_ffmpegdemo_FfmpegKit */

#ifndef _Included_com_sherry_ffmpegdemo_FfmpegKit
#define _Included_com_sherry_ffmpegdemo_FfmpegKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sherry_ffmpegdemo_FfmpegKit
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sherry_ffmpegdemo_FfmpegKit_run
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_sherry_ffmpegdemo_FfmpegKit
 * Method:    configure
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sherry_ffmpegdemo_FfmpegKit_configure
  (JNIEnv *, jclass);

/*
 * Class:     com_sherry_ffmpegdemo_FfmpegKit
 * Method:    getSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sherry_ffmpegdemo_FfmpegKit_getSecret
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
